### ISSUE TITLE
Couldn't download PPA key

### ISSUE THREAD

**Issue by chazzly** [girder/ansible-role-girder-mongodb#10]
Running this against a VM running Bionic, I was not able to download the PPA key - kept giving me a connection timeout.  After some digging, apparently, this is due to a firewall blocking the standard port.   I changed the keyserver in the first task from:
"keyserver.ubuntu.com" to "hkp://keyserver.ubuntu.com:80" and it worked without a problem.
Figured this was worth sharing and it seems like an innocent enough change.

See https://unix.stackexchange.com/questions/75892/keyserver-timed-out-when-trying-to-add-a-gpg-public-key for reference.

**Comment by brianhelba** [comment]
@chazzly Thanks for the report. This should now be fixed.
